name: new-version

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:

  check-repo:
    runs-on: ubuntu-latest
    name: 'Check is this action in particular repo'
    if: ${{ github.event.repository.name == 'open-in-vscode-workflow' }}
    steps:
      - name: 'Print action info'
        run: echo "event=${{ github.event_name }} event_ref=${{ github.event.ref }} repo=${{ github.event.repository.full_name }}"

  publish:
    name: Build all workflow files and publish
    needs: check-repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: 'Build'
        run: ./scripts/github-workflow-build.sh --all
      - uses: actions/upload-artifact@v4
        with:
          name: workflow-files
          path: dist/*.alfredworkflow
          if-no-files-found: error
      - name: Publish package to NPM
        run: yarn npm publish
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
